kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-pv
  labels:
    type: iscsi
    app: redis
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.3.15:3260
    iqn: iqn.2020-09.com.example:host01
    lun: 0
    fsType: xfs
    readOnly: false

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-pvc
  labels:
    app: redis
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: redis-deployment
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:5.0.8-alpine
        livenessProbe:
          tcpSocket:
            port: 6379
        volumeMounts:
        - name: redisdata
          mountPath: /data
      volumes:
      - name: redisdata
        persistentVolumeClaim:
          claimName: redis-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: redis-srv
spec:
  type: NodePort
  selector:
    app: redis
  ports:
  - port: 6399
    targetPort: 6379
    nodePort: 30379

